# Generated by Django 6.0.7 on 2026-07-23 08:30

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('source_pdf', models.FileField(upload_to='uploads/sources/')),
                ('template_dir', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('analyzing', 'Analyzing'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('total_pages', models.PositiveIntegerField(blank=True, null=True)),
                ('primary_color', models.CharField(blank=True, max_length=30)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='uploads/thumbs/')),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('html_file', models.FileField(blank=True, null=True, upload_to='output/html/')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='output/pdf/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.template')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
