# Generated by Django 6.0.7 on 2026-08-02 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_generateddocument_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generateddocument',
            name='mode',
            field=models.CharField(choices=[('fill', 'Template Fill'), ('style', 'Style Clone')], default='fill', max_length=10),
        ),
    ]
